title: Robot Deployment / DevOps Engineer
company: Apptronik
category:
- Computer Vision
- Hardware
- Machine Learning
- Robotics
- Software
location: Austin, Texas, USA
date_posted: '2026-03-09'
description_html: '<p><p>Apptronik is a human-centered robotics company developing
  AI-powered robots to support humanity in every facet of life. Our flagship humanoid
  robot, Apollo, is built to collaborate thoughtfully with people, starting with critical
  industries such as manufacturing and logistics, with future applications in healthcare,
  the home, and beyond.<br>We operate at the cutting edge of embodied AI, applying
  our expertise across the full robotics stack to solve some of society''s most important
  problems. You will join a team dedicated to bringing Apollo to market at scale,
  tackling the complex challenges like safety, commercialization, and mass production
  to change the world for the better.</p></p><p><strong>Job Summary</strong><br>We
  are looking for a sharp, reliable Robot Deployment / DevOps Engineer to join our&nbsp;Operations
  team.&nbsp;In this role, you will own robot provisioning, configuration management,
  firmware/softwareupdates, and deployment workflows. Also responsible for the design
  and building of automated&nbsp;tools and processes to ensure consistent, and scalable
  deployments, both internal and for&nbsp;customer locations.</p><p><strong>ESSENTIAL
  DUTIES AND RESPONSIBILITIES</strong></p><ul><li>Build automation tools/scripts for
  robot onboarding and configuration.</li><li>Manage version control, update pipelines,
  rollback procedures, and change governance.</li><li>Create standardized deployment
  documentation, checklists, and readiness processes.</li><li>Partner with Field Service
  teams to execute customer-site deployments.</li><li>Develop CI/CD-inspired processes
  for fleet-wide robot updates and configuration Management.</li><li>Deployment of
  newly delivered robots to our Robot Park.

  <ul><li>Connect robots to computers and network</li><li>Test to ensure no hardware,
  firmware, or software issues exist</li><li>Upgrade software / firmware</li><li>Responsible
  for Deployment &lt;&gt; Engineering feedback loop to capture all deployment related
  requirements.</li></ul></li></ul><br><ul><li>Provide support for report deployments
  (travel)

  <ul><li>Ensure network connectivity</li><li>Provide Software support to ensure stability</li></ul></li></ul><br><p><strong>SKILLS
  AND REQUIREMENTS</strong></p><ul><li>Bachelor’s degree in Computer Science, Computer
  Engineering, or a related field, or equivalent practical experience</li><li>2-4+
  years in DevOps, automation, robotics, or systems integration.</li><li>Strong scripting
  skills (Python, Bash) and experience with configuration management.</li><li>Advanced
  knowledge and experience with Ansible, Linux, ROS, Python, C++, and Docker</li><li>Familiarity
  with robotics, embedded systems, or OTA update systems preferred.</li><li>1+ years
  network engineering experience (Cisco, Aruba, Ubiquiti, Meraki, etc.).</li></ul><br><p><strong>Nice
  to Have</strong></p><ul><li>Previous experience in robotics.</li><li>Experience
  working in a startup environment.</li></ul><p><strong>The Logistics</strong></p><ul><li>Location:
  This role is 100% on-site at our Austin, TX headquarters</li><li>Travel: Some travel
  is required, both domestic and foreign for this role. Ability to travel,&nbsp;and
  possession of passport is required.</li><li>Schedule: This role requires flexibility.
  Hours may vary, and may include evenings&nbsp;and/or weekends.</li></ul><p><br><br><p>*This
  is a direct hire.&nbsp; Please, no outside Agency solicitations.&nbsp;</p><p>Apptronik
  provides equal employment opportunities to all employees and applicants for employment
  and prohibits discrimination and harassment of any type without regard to race,
  color, religion, age, sex, national origin, disability status, genetics, protected
  veteran status, sexual orientation, gender identity or expression, or any other
  characteristic protected by federal, state or local laws.</p></p>'
description_text: 'Apptronik is a human-centered robotics company developing AI-powered
  robots to support humanity in every facet of life. Our flagship humanoid robot,
  Apollo, is built to collaborate thoughtfully with people, starting with critical
  industries such as manufacturing and logistics, with future applications in healthcare,
  the home, and beyond. We operate at the cutting edge of embodied AI, applying our
  expertise across the full robotics stack to solve some of society''s most important
  problems. You will join a team dedicated to bringing Apollo to market at scale,
  tackling the complex challenges like safety, commercialization, and mass production
  to change the world for the better. Job Summary We are looking for a sharp, reliable
  Robot Deployment / DevOps Engineer to join our&nbsp;Operations team.&nbsp;In this
  role, you will own robot provisioning, configuration management, firmware/softwareupdates,
  and deployment workflows. Also responsible for the design and building of automated&nbsp;tools
  and processes to ensure consistent, and scalable deployments, both internal and
  for&nbsp;customer locations. ESSENTIAL DUTIES AND RESPONSIBILITIES Build automation
  tools/scripts for robot onboarding and configuration. Manage version control, update
  pipelines, rollback procedures, and change governance. Create standardized deployment
  documentation, checklists, and readiness processes. Partner with Field Service teams
  to execute customer-site deployments. Develop CI/CD-inspired processes for fleet-wide
  robot updates and configuration Management. Deployment of newly delivered robots
  to our Robot Park. Connect robots to computers and network Test to ensure no hardware,
  firmware, or software issues exist Upgrade software / firmware Responsible for Deployment
  &lt;&gt; Engineering feedback loop to capture all deployment related requirements.
  Provide support for report deployments (travel) Ensure network connectivity Provide
  Software support to ensure stability SKILLS AND REQUIREMENTS Bachelor’s degree in
  Computer Science, Computer Engineering, or a related field, or equivalent practical
  experience 2-4+ years in DevOps, automation, robotics, or systems integration. Strong
  scripting skills (Python, Bash) and experience with configuration management. Advanced
  knowledge and experience with Ansible, Linux, ROS, Python, C++, and Docker Familiarity
  with robotics, embedded systems, or OTA update systems preferred. 1+ years network
  engineering experience (Cisco, Aruba, Ubiquiti, Meraki, etc.). Nice to Have Previous
  experience in robotics. Experience working in a startup environment. The Logistics
  Location: This role is 100% on-site at our Austin, TX headquarters Travel: Some
  travel is required, both domestic and foreign for this role. Ability to travel,&nbsp;and
  possession of passport is required. Schedule: This role requires flexibility. Hours
  may vary, and may include evenings&nbsp;and/or weekends. *This is a direct hire.&nbsp;
  Please, no outside Agency solicitations.&nbsp; Apptronik provides equal employment
  opportunities to all employees and applicants for employment and prohibits discrimination
  and harassment of any type without regard to race, color, religion, age, sex, national
  origin, disability status, genetics, protected veteran status, sexual orientation,
  gender identity or expression, or any other characteristic protected by federal,
  state or local laws.'
hiring_remote_in: ''
workplace_type: ''
salary_range_short: ''
seniority: Mid
workplace_type_enum: UNKNOWN
company_overview: Apptronik is building robots for the real world to improve human
  quality of life and to help solve the ever-increasing labor shortage problem. Our
  team has been building some of the most advanced robots on the planet for years,
  dating back to the DARPA Robotics Challenge. We apply our expertise across the full
  robotics stack to some of the most important and impactful problems our society
  faces, and expect our products and technology to change the world for the better.
  We value passion, creativity, and collaboration to help us overcome existing technological
  barriers in the industry to create truly innovative products.
url: https://builtin.com/job/robot-deployment-devops-engineer/8694719
source: builtin.com
description: 'Apptronik is a human-centered robotics company developing AI-powered
  robots to support humanity in every facet of life. Our flagship humanoid robot,
  Apollo, is built to collaborate thoughtfully with people, starting with critical
  industries such as manufacturing and logistics, with future applications in healthcare,
  the home, and beyond. We operate at the cutting edge of embodied AI, applying our
  expertise across the full robotics stack to solve some of society''s most important
  problems. You will join a team dedicated to bringing Apollo to market at scale,
  tackling the complex challenges like safety, commercialization, and mass production
  to change the world for the better. Job Summary We are looking for a sharp, reliable
  Robot Deployment / DevOps Engineer to join our&nbsp;Operations team.&nbsp;In this
  role, you will own robot provisioning, configuration management, firmware/softwareupdates,
  and deployment workflows. Also responsible for the design and building of automated&nbsp;tools
  and processes to ensure consistent, and scalable deployments, both internal and
  for&nbsp;customer locations. ESSENTIAL DUTIES AND RESPONSIBILITIES Build automation
  tools/scripts for robot onboarding and configuration. Manage version control, update
  pipelines, rollback procedures, and change governance. Create standardized deployment
  documentation, checklists, and readiness processes. Partner with Field Service teams
  to execute customer-site deployments. Develop CI/CD-inspired processes for fleet-wide
  robot updates and configuration Management. Deployment of newly delivered robots
  to our Robot Park. Connect robots to computers and network Test to ensure no hardware,
  firmware, or software issues exist Upgrade software / firmware Responsible for Deployment
  &lt;&gt; Engineering feedback loop to capture all deployment related requirements.
  Provide support for report deployments (travel) Ensure network connectivity Provide
  Software support to ensure stability SKILLS AND REQUIREMENTS Bachelor’s degree in
  Computer Science, Computer Engineering, or a related field, or equivalent practical
  experience 2-4+ years in DevOps, automation, robotics, or systems integration. Strong
  scripting skills (Python, Bash) and experience with configuration management. Advanced
  knowledge and experience with Ansible, Linux, ROS, Python, C++, and Docker Familiarity
  with robotics, embedded systems, or OTA update systems preferred. 1+ years network
  engineering experience (Cisco, Aruba, Ubiquiti, Meraki, etc.). Nice to Have Previous
  experience in robotics. Experience working in a startup environment. The Logistics
  Location: This role is 100% on-site at our Austin, TX headquarters Travel: Some
  travel is required, both domestic and foreign for this role. Ability to travel,&nbsp;and
  possession of passport is required. Schedule: This role requires flexibility. Hours
  may vary, and may include evenings&nbsp;and/or weekends. *This is a direct hire.&nbsp;
  Please, no outside Agency solicitations.&nbsp; Apptronik provides equal employment
  opportunities to all employees and applicants for employment and prohibits discrimination
  and harassment of any type without regard to race, color, religion, age, sex, national
  origin, disability status, genetics, protected veteran status, sexual orientation,
  gender identity or expression, or any other characteristic protected by federal,
  state or local laws.'
postedDate: '2026-03-09'
id: '2'
is_gtm_technical: true
tech_stack:
- Python
- Bash
- Ansible
- ROS
- Docker
min_years_exp: 2
salary_min: 0
salary_max: 0
reason: Role centers on technical DevOps responsibilities in robot deployment and
  management.
